server:
  port: 11000

spring:
  application:
    name: notes-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: core-user
          uri: lb://core-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone:
        http://${eureka.instance.hostname}:10001/eureka/