server:
  port: 9001

spring:
  application:
    name: core-user
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/core-user?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.126.com
    username: nueiaaa@126.com
    password: zq2536999m
    default-encoding: UTF-8
    properties: 
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone:
        http://${eureka.instance.hostname}:10001/eureka/